### PR TITLE
remove and add: text shadow and underline

### PR DESCRIPTION
**Pull request by lucie07**

### CODE REVIEW

**Comment by jmiguelv** [comment]
Thank you, there is a lot of repetition in the code, do you think you can try to clean it up? Also, what does (gitpod) in the commit messages mean?

**Comment by lucie07** [comment]
> Thank you, there is a lot of repetition in the code, do you think you can try to clean it up? Also, what does (gitpod) in the commit messages mean?

They are lengthy and it's not ideal, I tried to use less code but each css section links with one heading, I can remove some comment lines if that makes it tidier? (gitpod) means the commits were made in gitpod and not in codespaces, sorry I will avoid confusing titles

**Comment by jmiguelv** [comment]
You could combine most of the code into one class, and have the widths in separate classes. Also because this is using sass, you can combine things to reduce repetition, you would end up with something like:

```
h2.underline-with-shadow {
  ...

  &::after {
    ...
  }
}
```

The underlines don't need to be different widths. @ongtiffany does this make sense to you?

Re commit messages, there is no need to specify where the commit came from. (A reminder on commit messages https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by lucie07** [comment]
> You could combine most of the code into one class, and have the widths in separate classes. Also because this is using sass, you can combine things to reduce repetition, you would end up with something like:
> 
> ```sass
> h2.underline-with-shadow {
>   ...
> 
>   &::after {
>     ...
>   }
> }
> ```
> 
> The underlines don't need to be different widths. @ongtiffany does this make sense to you?
> 
> Re commit messages, there is no need to specify where the commit came from. (A reminder on commit messages https://www.conventionalcommits.org/en/v1.0.0/)

Thank you Miguel, I cleaned it up a bit and made a new commit, is it still look too much? I think underlines can have the same widths, if Tiffany think so too I can remove different widths. Thanks for commit messages reminder, will follow them then

**Comment by jmiguelv** [comment]
You should only need one class and one pseudo element since the styling is the same for all the headings. You could even do without using a class and style the h2 directly, but at the moment there are 3 different classes doing exactly the same.

**Comment by lucie07** [comment]
> You should only need one class and one pseudo element since the styling is the same for all the headings. You could even do without using a class and style the h2 directly, but at the moment there are 3 different classes doing exactly the same.

Thanks Miguel I removed unnecessary class and kept the elements in h2, if that looks okay for you

**Review by jmiguelv — APPROVED** [review]

**Pull request merged**
